---
# ------------------------------------------------------------------------------
# Driver script to configure Goldengate on XEN VMs
# ------------------------------------------------------------------------------
- name:                 "Configure XEN server and start GoldenGate VMs"
  ansible.builtin.import_playbook: start_xen_vms.yml

- name:                 "Install and configure GoldenGate"
  ansible.builtin.import_playbook: install_goldengate.yml
...
