---
# ------------------------------------------------------------------------------
# Install and configure Oracle GoldenGate (OGG) Microservices
# ------------------------------------------------------------------------------

- hosts:                all
  tasks:

  - name:               "Create directory for OGG Installer"
    file:
      name:             "{{ installer_dir }}"
      group:            "{{ install_group }}"
      owner:            oracle
      state:            directory
      mode:             0775
    become:             yes
    become_user:        oracle

  - name:               "Unzip Oracle GoldenGate Installer"
    unarchive:
      creates:          "{{ installer_bin }}"
      dest:             "{{ installer_dir }}"
      group:            "{{ install_group }}"
      owner:            oracle
      remote_src:       yes
      src:              "{{ sw_archive }}"
    become:             yes
    become_user:        oracle
 
  - name:               "Generate Response File and scripts"
    template:
      src:              "{{ item.dest | basename  }}.j2"
      dest:             "{{ item.dest }}"
      mode:             "{{ item.mode }}"
    become:             yes
    become_user:        oracle
    with_items:
      - { dest: "{{ response_file }}", mode: "0600" }
      - { dest: "{{ apply_patch_script }}", mode: "0700" }
  
  - name:               "Perform a Silent Installation"
    command:
      argv:
        -               "{{ installer_bin }}"
        -               "-silent"
        -               "-waitForCompletion"
        -               "-responseFile"
        -               "{{ response_file }}"
      creates:          "{{ software_location }}"
    register:           ogg_install
    become:             yes
    become_user:        oracle

  - name:               "Display output from silent installation"
    debug:
      var:              ogg_install.stdout_lines
    when:               ogg_install.stdout_lines is defined

  - name:               "Allow OGG to pass through firewall"
    firewalld:
      permanent:        yes
      port:             "{{ item }}"
      state:            enabled
      zone:             public
    with_items:
      -                 "{{ manager_port }}/tcp"
      -                 "{{ manager_port }}/udp"
    become:             yes
    become_user:        root
    notify:             "Reload FireWall Rules"

  - name:               "Verify existence of OPatch utility"
    stat:
      path:             "{{ opatch_bin }}"
    register:           opatch_stat

  - name:               "Apply patch if it has not been applied"
    block:

    - name:             "Get current patches"
      command:
        argv:
          -             "{{ opatch_bin }}"
          -             "lsinventory"
      become:           yes
      become_user:      oracle
      register:         patch_inventory

    - name:             "Patch {{ patch_number }} needs to be applied"
      block:
      
      - name:           "Create Extraction Directory"
        file:
          path:         "{{ software_location }}/patches/P{{ patch_number }}"
          group:        "{{ install_group }}"
          owner:        oracle
          state:        directory
          mode:         '775'

      - name:           "Unzip Oracle Patch {{ patch_number }}"
        unarchive:
          creates:      "{{ software_location }}/patches/P{{ patch_number }}/{{ patch_number }}"
          dest:         "{{ software_location }}/patches/P{{ patch_number }}"
          group:        "{{ install_group }}"
          owner:        oracle
          remote_src:   yes
          src:          "{{ patch_archive_loc }}/p{{ patch_number }}_{{ version }}_{{ platform }}.zip"

      - name:           "Apply patch {{ patch_number }}"
        command:
          argv:
            -           "{{ apply_patch_script }}"
            -           "{{ patch_number }}"
        register:       apply_patch

      - name:           "Display output from apply of patch {{ patch_number }}"
        debug:
          var:          apply_patch.stdout_lines
        when:           apply_patch.stdout_lines is defined

      become:           yes
      become_user:      oracle
      when:
        -               patch_inventory.stdout is defined
        -               patch_inventory.stdout is not search(patch_number)

    when:
      -                 opatch_stat.stat is defined
      -                 opatch_stat.stat.exists
# ------------------------------------------------------------------------------
# Handlers
# ------------------------------------------------------------------------------

  handlers:

  - name:               "Reload FireWall Rules"
    command:
      argv:
        -               firewall-cmd
        -               "--reload"
    become:             yes
    become_user:        root
...
