---
# ------------------------------------------------------------------------------
# Host specific variables for GOLDENGATE1
# ------------------------------------------------------------------------------

SID:                    "GG1V19C"
PDBName:                "GG1A"
globalDBName:           "GG1CDB19C.YAOCM.ID.AU"

...
